sudo: required

language: cpp

notifications:
  email: false

compiler:
  - gcc
  - clang

arch:
  packages:
    - meson
    - ninja
    - valgrind
  script: 
    - meson build -Dtests=true -Dsample=true
    - ninja -C build
    - meson test -C build --wrapper 'valgrind --leak-check=full' -v

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
