sudo: required
language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -y install meson ninja valgrind

script:
  - meson build -Dtests=true -Dsample=true
  - ninja -C build
  - meson test -C build --wrapper 'valgrind --leak-check=full --error-exitcode=1' --print-errorlogs
