sudo: required

language: cpp

notifications:
  email: false

compiler:
  - gcc
  - clang

arch:
  packages:
    - meson
    - ninja
    - valgrind
  script:
    - meson build -Dtests=true
    - cd build
    - ninja
    - meson test --wrapper valgrind
    - "cat meson-logs/testlog-valgrind.txt | : "

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
