os: linux
dist: bionic
language: cpp

compiler:
  - clang
  - gcc

install:
  - pip install meson ninja

script:
  - meson build -Dtests=true -Dsample=true
  - ninja -C build
  - meson test -C build --wrapper 'valgrind --leak-check=full --error-exitcode=1' --print-errorlogs
